name: gemini-action
description: Github Action for gemini
author: kt

branding:
  icon: heart
  color: red
inputs:
  token:
    description: gemini token
    required: true
  model:
    description: gemini model
    required: false
    default: "gemini-2.0-flash"
  prompt:
    description: prompt
    required: true
  system-prompt:
    description: high level prompt
    required: false
  temperature:
    description: temperature
    default: 0.6
    required: false
  topP:
    description: topP
    default: 0.95
    required: false
  topK:
    description: topK
    default: 40
    required: false
  maxOutputTokens:
    description: maxOutputTokens
    default: 65536
    required: false
  responseMime:
    description: responseMime
    default: text/plain
    required: false
  responseSchema:
    description: responseSchema in json
    required: false
  file-path:
    description: file path (only single file now)
    required: false
  file-mime:
    description: file mime
    required: false

outputs:
  output:
    description: output
runs:
  using: node20
  main: dist/index.js
