name: Scrape

on:
  push:
    branches:
      - main

jobs:
  scrape:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run scraping script
        run: |
          python scrape.py

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: scraped-data
          path: data/